#!/usr/bin/env node
/**
 * Bundle built-in skills from real files on disk into a TypeScript module.
 *
 * Sources:
 *  - the `kepler` skill comes from the installed `@kepler.gl/mcp` package
 *    (`skill/kepler/`), so the map.* skill lives in the repo that owns the
 *    map commands. This repo's harness-specific notes
 *    (`scripts/kepler-skill.harness.md`) are appended to its SKILL.md.
 *  - every other skill comes from `skills/built-in/<id>/` in this repo.
 *
 * Each source directory is expected to contain `skill.yaml` and `SKILL.md`
 * (plus any optional extra files). Emits `src/chat/bundledSkills.ts`
 * containing a `BUNDLED_SKILLS` array of seed skill objects; `seedSkills.ts`
 * re-exports this as the assistant's default `SEED_SKILLS`.
 *
 * Run automatically as a prebuild step (see package.json `build` script), or
 * manually: `node scripts/generate-skills.mjs`
 */

import {existsSync, readdirSync, readFileSync, writeFileSync, statSync} from 'node:fs';
import {createRequire} from 'node:module';
import {join, dirname} from 'node:path';
import {fileURLToPath} from 'node:url';

const require = createRequire(import.meta.url);
const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const SKILLS_DIR = join(ROOT, 'skills/built-in');
const OUTPUT = join(ROOT, 'src/chat/bundledSkills.ts');
const ROOT_ID = 'built-in';
const MCP_SKILL_ID = 'kepler';
const HARNESS_FILE = join(__dirname, 'kepler-skill.harness.md');

/**
 * @param {string} dir
 * @returns {{relativePath: string, content: string}[]}
 */
function readSkillFiles(dir) {
  const entries = readdirSync(dir);
  const files = [];
  for (const name of entries) {
    const fullPath = join(dir, name);
    if (statSync(fullPath).isFile()) {
      files.push({relativePath: name, content: readFileSync(fullPath, 'utf8')});
    }
  }
  return files;
}

/**
 * Resolve the `@kepler.gl/mcp` package root and return the path to its
 * `skill/kepler` directory. Works through pnpm's `file:` symlink: we resolve
 * the package's main entry (dist/index.js) and walk up to the package root,
 * falling back to a node_modules walk for the case where `dist` is not yet
 * built.
 */
function resolveMcpSkillDir() {
  // 1) Through the package main entry (realpath of the file: symlink).
  try {
    const entry = require.resolve('@kepler.gl/mcp'); // <pkg>/dist/index.js
    const candidate = join(dirname(dirname(entry)), 'skill', MCP_SKILL_ID);
    if (existsSync(join(candidate, 'SKILL.md'))) return candidate;
  } catch {
    // package main not resolvable (dist not built yet) — fall through
  }
  // 2) Walk up for a node_modules/@kepler.gl/mcp symlink.
  let dir = ROOT;
  while (dirname(dir) !== dir) {
    const candidate = join(dir, 'node_modules', '@kepler.gl', 'mcp', 'skill', MCP_SKILL_ID);
    if (existsSync(join(candidate, 'SKILL.md'))) return candidate;
    dir = dirname(dir);
  }
  throw new Error(
    `Could not resolve the kepler skill from @kepler.gl/mcp (skill/${MCP_SKILL_ID}). ` +
      `Run "pnpm install" so the file: dependency is linked into node_modules, ` +
      `or confirm the skill exists in the package.`
  );
}

function main() {
  // Local skills, minus the one that ships with @kepler.gl/mcp.
  const localDirs = readdirSync(SKILLS_DIR)
    .map(name => ({name, path: join(SKILLS_DIR, name)}))
    .filter(entry => statSync(entry.path).isDirectory())
    .filter(entry => entry.name !== MCP_SKILL_ID)
    .sort((a, b) => a.name.localeCompare(b.name));

  const seeds = localDirs.map(({name: id, path}) => ({
    id,
    rootId: ROOT_ID,
    files: readSkillFiles(path)
  }));

  // Kepler skill from @kepler.gl/mcp, with harness notes appended.
  const keplerSkillDir = resolveMcpSkillDir();
  const keplerFiles = readSkillFiles(keplerSkillDir);
  if (existsSync(HARNESS_FILE)) {
    const harness = readFileSync(HARNESS_FILE, 'utf8');
    const skillMd = keplerFiles.find(f => f.relativePath === 'SKILL.md');
    if (skillMd) {
      skillMd.content = `${skillMd.content.replace(/\s+$/, '')}\n\n${harness}`;
    }
  }
  seeds.push({id: MCP_SKILL_ID, rootId: ROOT_ID, files: keplerFiles});
  seeds.sort((a, b) => a.id.localeCompare(b.id));

  const header = `// Auto-generated by scripts/generate-skills.mjs — DO NOT EDIT
import type {SkillFile} from '@sqlrooms/ai';

export interface BundledSeedSkill {
  id: string;
  rootId: string;
  files: SkillFile[];
}

export const BUNDLED_SKILLS: BundledSeedSkill[] = ${JSON.stringify(seeds, null, 2)};
`;

  writeFileSync(OUTPUT, header, 'utf8');
  console.log(
    `Generated ${OUTPUT} with ${seeds.length} skills: ${seeds.map(s => s.id).join(', ')}`
  );
}

main();
