#!/usr/bin/env node
/**
 * Bundle built-in skills from real files on disk into a TypeScript module.
 *
 * Sources:
 *  - the `kepler` skill comes from the map surface **vendored** at
 *    `src/mcp/skill/kepler/` (temporarily integrated from the kepler.gl
 *    `@kepler.gl/mcp` module, which permanently owns the map commands). This
 *    repo's harness-specific notes (`scripts/kepler-skill.harness.md`) are
 *    appended to its SKILL.md.
 *  - every other skill comes from `skills/built-in/<id>/` in this repo.
 *
 * Each source directory is expected to contain `skill.yaml` and `SKILL.md`
 * (plus any optional extra files). Emits `src/chat/bundledSkills.ts`
 * containing a `BUNDLED_SKILLS` array of seed skill objects; `seedSkills.ts`
 * re-exports this as the assistant's default `SEED_SKILLS`.
 *
 * Run automatically as a prebuild step (see package.json `build` script), or
 * manually: `node scripts/generate-skills.mjs`
 */

import {existsSync, readdirSync, readFileSync, writeFileSync, statSync} from 'node:fs';
import {join, dirname} from 'node:path';
import {fileURLToPath} from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const SKILLS_DIR = join(ROOT, 'skills/built-in');
const OUTPUT = join(ROOT, 'src/chat/bundledSkills.ts');
const ROOT_ID = 'built-in';
const MCP_SKILL_ID = 'kepler';
const HARNESS_FILE = join(__dirname, 'kepler-skill.harness.md');

/**
 * The vendored map-surface skill, temporarily integrated from the kepler.gl
 * `@kepler.gl/mcp` module. See NEXT_PLAN.md for the permanent separation.
 */
const MCP_SKILL_DIR = join(ROOT, 'src/mcp/skill/kepler');

/**
 * @param {string} dir
 * @returns {{relativePath: string, content: string}[]}
 */
function readSkillFiles(dir) {
  const entries = readdirSync(dir);
  const files = [];
  for (const name of entries) {
    const fullPath = join(dir, name);
    if (statSync(fullPath).isFile()) {
      files.push({relativePath: name, content: readFileSync(fullPath, 'utf8')});
    }
  }
  return files;
}

function main() {
  // Local skills, minus the one vendored at src/mcp/skill/kepler.
  const localDirs = readdirSync(SKILLS_DIR)
    .map(name => ({name, path: join(SKILLS_DIR, name)}))
    .filter(entry => statSync(entry.path).isDirectory())
    .filter(entry => entry.name !== MCP_SKILL_ID)
    .sort((a, b) => a.name.localeCompare(b.name));

  const seeds = localDirs.map(({name: id, path}) => ({
    id,
    rootId: ROOT_ID,
    files: readSkillFiles(path)
  }));

  // Kepler skill from the vendored map surface (src/mcp/skill/kepler), with
  // harness notes appended.
  const keplerSkillDir = MCP_SKILL_DIR;
  const keplerFiles = readSkillFiles(keplerSkillDir);
  if (existsSync(HARNESS_FILE)) {
    const harness = readFileSync(HARNESS_FILE, 'utf8');
    const skillMd = keplerFiles.find(f => f.relativePath === 'SKILL.md');
    if (skillMd) {
      skillMd.content = `${skillMd.content.replace(/\s+$/, '')}\n\n${harness}`;
    }
  }
  seeds.push({id: MCP_SKILL_ID, rootId: ROOT_ID, files: keplerFiles});
  seeds.sort((a, b) => a.id.localeCompare(b.id));

  const header = `// Auto-generated by scripts/generate-skills.mjs — DO NOT EDIT
import type {SkillFile} from '@sqlrooms/ai';

export interface BundledSeedSkill {
  id: string;
  rootId: string;
  files: SkillFile[];
}

export const BUNDLED_SKILLS: BundledSeedSkill[] = ${JSON.stringify(seeds, null, 2)};
`;

  writeFileSync(OUTPUT, header, 'utf8');
  console.log(
    `Generated ${OUTPUT} with ${seeds.length} skills: ${seeds.map(s => s.id).join(', ')}`
  );
}

main();
